<?php

/**
 * Created by PhpStorm.
 * User: jqz
 * Date: 2018/1/13
 * Time: 11:10
 */
namespace backend\modules\site;

class Module extends \yii\base\Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}