<?php

namespace console\controllers;

use common\models\mongodb\AdminLog;
use common\models\mysql\Admin;
use yii\mongodb\Query;

/**
 * Created by PhpStorm.
 * User: jqz
 * Date: 2018/2/8
 * Time: 22:57
 */
class SwooleTestController extends \yii\console\Controller
{
    protected $_serv = null;

    protected $_key = "^manks.top&swoole$";

    protected $_uid2fd = [];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if ($this->_serv === null) {
            $this->_serv = new \Swoole\WebSocket\Server('0.0.0.0', 9501);
            $this->_serv->set(
                [
                    'worker_num' => 2,
                    'heartbeat_check_interval' => 30,
                    'heartbeat_idle_time' => 90,
                ]
            );
            $this->_serv->on('open','onOpen');
            $this->_serv->on('message','onMessage');
            $this->_serv->on('close','onClose');
        }
    }
//
//    public function actionIndex()
//    {
//
//        $mapReduceOut = AdminLog::getCollection()->mapReduce(
//            'function(){emit(this.type,1)}',
//            'function(key,values){return Array.sum(values)}',
//            'mapReduceOut'
//        );
//        $query = new Query();
//        $result = $query->from($mapReduceOut)->all();
//        $arr = [
//            [
//                '$group' => ['_id' => '$type', 'count' => ['$sum' => 1]],
//            ]
//        ];
//        $res = AdminLog::getCollection()->aggregate($arr, ['cursor' => ['batchSize' => 1]])->toArray();
//    }

    protected function onOpen()
    {
    }
}