<?php
/**
 * Created by PhpStorm.
 * User: jqz
 * Date: 2018/1/13
 * Time: 11:32
 */

namespace backend\modules;


use yii\web\Controller;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}